<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishTrimmed>false</PublishTrimmed>
        <RootNamespace>AtomUIGallery.Icon.Application</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>GeneratedFiles</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs"/>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="Assets/Svg/**/*.svg"/>
    </ItemGroup>

    <ItemGroup Condition=" '$(Configuration)' == 'Release' ">
        <PackageReference Include="AtomUI.Core"/>
        <PackageReference Include="AtomUI.Icons.Generator"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"
                          PrivateAssets="all"/>
    </ItemGroup>
    
    <ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
        <ProjectReference Include="../../packages/AtomUI/src/AtomUI.Core/AtomUI.Core.csproj" />
        <ProjectReference Include="../../packages/AtomUI/src/AtomUI.Icons.Generator/AtomUI.Icons.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all" />
    </ItemGroup>

</Project>
